//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkLibraries.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankFeedsTestData
    {
        public string Test_Name { get; set; }
        public string Account { get; set; }
        public string Payee { get; set; }
        public string DownloadedAs_Search_String { get; set; }
        public string Customer_ID { get; set; }
        public string PIN { get; set; }
        public string OFX_Server { get; set; }
    }
}
