//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkLibraries.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_TestData
    {
        public string Customer_Job { get; set; }
        public string Template { get; set; }
        public string Ship_To { get; set; }
        public string PO_Number { get; set; }
        public string VIA { get; set; }
        public string FOB { get; set; }
        public string REP { get; set; }
        public string Qunatity { get; set; }
        public string Item { get; set; }
        public string Description { get; set; }
        public string Test_Name { get; set; }
        public string Class { get; set; }
        public string Account { get; set; }
    }
}
