//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkLibraries.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siebel_TestData
    {
        public string Product_Name { get; set; }
        public string Product_Version { get; set; }
        public string Product_Edition { get; set; }
        public string Fulfillment_Method { get; set; }
        public string Users { get; set; }
        public string License_Key { get; set; }
        public string Product_Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int ID { get; set; }
        public string AccountName { get; set; }
        public string CACI { get; set; }
        public string AuthID { get; set; }
        public string Email { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
    }
}
