//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkLibraries.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SQLCompactDBEntities : DbContext
    {
        public SQLCompactDBEntities()
            : base("name=SQLCompactDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BankFeedsTestData> BankFeedsTestDatas { get; set; }
        public DbSet<Invoice_TestData> Invoice_TestData { get; set; }
        public DbSet<Siebel_TestData> Siebel_TestData { get; set; }
        public DbSet<Test_Results> Test_Results { get; set; }
    }
}
